### ISSUE TITLE
download_catch_rates() creates values for "num" when add_zeros = TRUE

### ISSUE THREAD

**Issue by andrewdeines** [James-Thorson/FishData#11]
For example

DF = FishData::download_catch_rates(survey="West_coast_groundfish_bottom_trawl_survey", species_set="Platymera gaudichaudii")
head(DF[DF$Year==2003 & DF$Wt==0 & !is.na(DF$Num), ])

**Comment by lewisab** [comment]
The problem does not seem to be with add_zeros, because the numbers (abundance) does not match the values in the data warehouse even when add_zeros = FALSE.  The problem is that the area swept column in the query no longer exists in the data warehouse, or it was renamed as actual_station_design_dim$area_hectares ?

**Comment by lewisab** [comment]
Well, it appears that the area swept column is still in the haul information, so if that is getting extracted correctly then the problem is with this term which is multiplied by the CPUE in the attempt to obtain the raw catch and area swept as separate columns: outer(Downloaded_data[,'area_swept_ha_der'],c(1,1))

Maybe it should be: outer(Downloaded_data['area_swept_ha_der'],c(1,1))

**Comment by James-Thorson** [comment]
I'm not following and don't have time to give input. You could just put NAs
for the counts for WCGBTS?  Really we should prolly just ask John Wallace
if he'd maintain NWFSC repository interfacing code for this package

**Comment by James-Thorson** [comment]
solved by listing counts as NA in latest commit.
